name: my_flutter_app
description: A new Flutter project.
publish_to: 'none' # Убедитесь, что это указано, чтобы не публиковать в pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.4.0 # Добавьте зависимости, которые используете

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

